import type { Metadata } from "next";
import { GeistMono } from 'geist/font/mono'
import './global.css'
import { RootProvider } from 'xyzdoc-ui/provider/next'
import { Body } from '@/app/layout.client'
// import { NextProvider } from 'xyzdoc-core/framework/next'
// import { NextProvider } from 'fumadocs-core/framework/next'
import { TreeContextProvider } from 'xyzdoc-ui/contexts/tree'
import { Provider } from './provider'
import { source } from '@/lib/source'

 

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={GeistMono.variable} suppressHydrationWarning>
      <Body>
        <RootProvider>
          <TreeContextProvider tree={source.getPageTree()}>
            <Provider>{children}</Provider>
          </TreeContextProvider>
        </RootProvider>
      </Body>
    </html>
  )
}
